name       : Run Tests - Unit
on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies-poetry

      - name: Run Unit Tests
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/run-unit-tests@main
        with:
          package_name          : 'osbot_github'
          codecov_token         : ${{ secrets.CODECOV_TOKEN          }}
          #GIT_HUB__ACCESS_TOKEN : ${{ secrets.GIT_HUB__ACCESS_TOKEN  }}

